name: pack-backend
description: Packs up backend for deployment and uploads to artifact.


runs:
  using: composite
  steps:
    - run: 7z a ../lambda.zip $(pipenv --venv)/lib/python*/site-packages/*
      working-directory: ./backend
      shell: bash

    - run: 7z a ../lambda.zip migrations ../backend
      working-directory: ./backend
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: backend
        path: lambda.zip
        retention-days: 1
