name: pack-backend
description: Packs up backend for deployment and uploads to artifact.


runs:
  using: composite
  steps:
    - uses: ./.github/actions/set-env-var
      with:
        name: my_installed_packages
        command: pipenv run python -c 'import site; print(site.getsitepackages()[0])'

    - run: 7z a ../lambda.zip ${{ env.my_installed_packages }}
      working-directory: ./backend
      shell: bash

    - run: 7z a ../lambda.zip -xr'!.venv' migrations ../backend
      working-directory: ./backend
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: backend
        path: lambda.zip
        retention-days: 1
        if-no-files-found: error
