name: setup-backend
description: Sets up runner environment according to backend code needs


inputs:
  python-version:
    description: "Python version to use. Example '3.8'"
    default: '3.8'
    required: false
    type: string
  pipenv-version:
    description: "Pipenv version to use. Example '2022.1.8'"
    default: '2022.1.8'
    required: false
    type: string
  pipenv-lockfile:
    description: "Full path to pipenv lockfile. Example 'backend/Pipfile.lock'"
    default: 'backend/Pipfile.lock'
    required: false
    type: string


runs:
  using: composite
  steps:
    # configure python as specified in the input
    - uses: actions/setup-python@v2
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    

    # set some helpful temporary variables
    - uses: ./.github/actions/set-env-var
      with:
        name: my_python
        value: python${{ inputs.python-version }}
    
    - uses: ./.github/actions/set-env-var
      with:
        name: my_cache_prefix
        value: ${{ runner.os }}-${{ env.my_python }}
    
    - uses: ./.github/actions/set-env-var
      with:
        name: my_pipenv_hash_path
        value: ~/.local/${{ env.my_python }}/site-packages/pipenv/__version__.py

    - run: pip install pipenv=="${{ inputs.pipenv-version }}"
      shell: bash
    

    - run: python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
      shell: bash

    - run: python3 -c 'import site; print(site.getsitepackages())'
      shell: bash

    - run: python3 -c 'import pipenv; print(pipenv.__file__)'
      shell: bash

    - run: python3 -c 'import pipenv; print(pipenv.__path__)'
      shell: bash
    
    - run: python3 -m site --user-site
      shell: bash

    - run: python3 -m site --user-base
      shell: bash

    - run: python3 -m site
      shell: bash

#/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pipenv/__version__.py


    - run: ls ~/.local/${{ env.my_python }}
      shell: bash


    # set up cache for pipenv installation and conditionally install it
    - uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.local/${{ env.my_python }}/site-packages/pipenv
        key: ${{ env.my_cache_prefix }}-pip-${{ hashFiles(format('{0}', env.my_pipenv_hash_path)) }}
        restore-keys: ${{ env.my_cache_prefix }}-pip-

    - run: pip install pipenv=="${{ inputs.pipenv-version }}"
      if: steps.cache-pip.outputs.cache-hit == 'false'
      shell: bash


    # set up cache for dependencies and conditionally install them
    - uses: actions/cache@v2
      id: cache-pipenv
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ env.my_cache_prefix }}-pipenv-${{ hashFiles(format('{0}', inputs.python-lockfile)) }}
        restore-keys: ${{ env.my_cache_prefix }}-pipenv-

    - run: pipenv install --dev --deploy
      if: steps.cache-pipenv.outputs.cache-hit == 'false'
      shell: bash
