name: backend


on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'


jobs:
  backend:
    name: lint and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: ./.github/actions/setup-backend

      - run: pipenv run black --check .
      - run: pipenv run pytest
        env:
          FLASK_APP: 'app.py'
          FLASK_ENV: 'development'
          SECRET_KEY: 'codeforpoznan'
          BASE_URL: 'localhost'
          DB_HOST: 'db'
          DB_PORT: '5432'
          DB_NAME: 'cfp_v3'
          DB_USER: 'cfp_v3'
          DB_PASSWORD: 'cfp_v3'
          MAIL_SERVER: ''
          MAIL_PORT: ''
          MAIL_USERNAME: ''
          MAIL_PASSWORD: ''
          MAIL_SUPPRESS_SEND: 'TRUE'

      - uses: ./.github/actions/pack-backend
        if: github.event_name == 'push'
