name: check-path


on:
  workflow_call:
    outputs:
      frontend:
        value: ${{ jobs.check-path.outputs.frontend }}
      backend:
        value: ${{ jobs.check-path.outputs.backend }}


jobs:
  check-path:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.frontend.outputs.modified }}
      backend: ${{ steps.backend.outputs.modified }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: ./.github/actions/set-env-var
        with:
          name: my_frontend_check
          command: git diff-index --name-only HEAD | grep ^frontend/

      - uses: ./.github/actions/set-env-var
        with:
          name: my_backend_check
          command: git diff-index --name-only HEAD | grep ^backend/

        run: echo "::set-output name=modified::${{ env.my_frontend_check }}"
        id: frontend

      - run: echo "::set-output name=modified::${{ env.my_backend_check }}"
        id: backend
